- hosts: all
  gather_facts: no
  remote_user: odroid
  #become: yes
  tasks:
  - name: "copyfile"
    copy:
     src: minimap.sh
     dest: /tmp/minimap.sh
     #owner: odroid
     #group: odroid
     mode: 0744
  - name: "run"
    shell: /tmp/minimap.sh 2> /genomics/scratch/log.txt
    #command: ls

