- hosts: all
  gather_facts: no
  remote_user: odroid
  tasks:
  - name: "dic"
    shell: java -Xmx1500M -jar /genomics/gatk/picard.jar CreateSequenceDictionary REFERENCE=/genomics/reference/human-genome.fa OUTPUT=/genomics/reference/human-genome.dict 

