- hosts: all
  gather_facts: no
  remote_user: odroid
  #become: yes
  tasks:
  - name: "copyfile"
    copy:
     src: sorter.sh
     dest: /tmp/sorter.sh
     #owner: odroid
     #group: odroid
     mode: 0744
  - name: "run"
    shell: /tmp/sorter.sh 2> /genomics/scratch/sorterr.txt
    #command: ls

