- hosts: all
  gather_facts: no
  remote_user: odroid
  become: yes
  tasks:
  - name: "removeline"
    lineinfile:
     dest: /etc/fstab
     regexp: '^192.168.1.10:/storage'
     state: absent
     #line: 'tmpfs   /ramdisk tmpfs   nodev,nosuid,noexec,nodiratime,size=400M   0 0'
     #line: '192.168.1.10:/storage     /storage   nfs     intr,nfsvers=4,rsize=8192,wsize=8192       0       0'		
